### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by geangs** [MizunagiKB/gd_cubism#11]
Would it be possible to share an example project with everything already set up? I think this would make it easier for users to test the code in their own projects. Thank you.

**Comment by MizunagiKB** [comment]
You're right.
If I add some Live2D model to the repository, anyone can check it immediately.

However, there is a reason why I have not uploaded the Live2D model.

Because I don't have a sense of drawing.
...But my current policy is to prevent unintentional Live2D models from getting mixed into your environment.

> This policy may change in the future.


If you do not have a Live2D model, you can download it from the Live2D official website.
I am using Niziiro Mao to check the operation.

https://www.live2d.com/en/download/sample-data/

**Comment by geangs** [comment]
I mean not just an example model but also a full project where it's not necessary to compile anything

**Comment by MizunagiKB** [comment]
Oh, I'm sorry.
I misunderstood the intent of your comment.

For example, you mean to provide the following?
* Download from Godot AssetLib.
* Attach the compiled binaries to the Releases on GitHub.

I would do so if I could, but GDCubism is linked to Live2D's libraries in the process of creating the executable binaries.

This library is licensed by Live2D and in principle is only allowed to be distributed under a commercial agreement.

I am not familiar with the law.
So, I asked the Live2D forum for a better distribution format.

As a result, I was given an example of a distribution format that would not violate the license, and I decided that it would not cause any violation of the license by the user.

I have seen people say,

> I would like to use Live2D with Godot Engine, but it is difficult to set up.

However, the least I can do now is to simplify the build procedure and try to explain it in detail.

**Comment by geangs** [comment]
I understand. I didn't realize their liscencing model may not allow this. Thank you for your work

**Comment by MizunagiKB** [comment]
I am glad that you can comment.
I appreciate your suggestions to make it better.

**Comment by MizunagiKB** [comment]
As a week has elapsed, we will now proceed to close this issue.
