### ISSUE TITLE
When part opacity is below 100%, the texture appears much darker than in the official viewer

### ISSUE THREAD

**Issue by Jueast** [MizunagiKB/gd_cubism#113]
Godot version: v4.3.stable.official [77dcf97d8]
gd_cubsim version: the latest main [d2e526f](https://github.com/MizunagiKB/gd_cubism/commit/d2e526f9eb949a3e3657117918ea24bff191a159)

As mentioned in the title, when I set the opacity of certain parts below 100%, the texture rendered by gd_cubism appears different from that in the Cubism Viewer, please check the screenshots below.

Parts Setting:

![image](https://github.com/user-attachments/assets/a56d5730-7b72-44e6-931c-45e18d8b7c56)

CubsimViewer and gd_cubsim results:

![image](https://github.com/user-attachments/assets/f2e18758-6ad7-4b95-89d3-e2086761cc9a)

After investigation, i found that it may relate to the "pre-multiplied alpha", like [this](https://docs.live2d.com/en/cubism-sdk-manual/texture-trouble-shooting/). The double multiplication of alpha values lead to the wrong display. So I try to change the switch in code [in my commit](https://github.com/Jueast/gd_cubism/commit/b1115941b90326cc161e53b46c1a38062966d8b4). After that, everything is ok, at least from my perspective.

But I still have questions: **Why gd_cubism set IsPreMultipliedAlpha to `true` here? Or is there any more correct method to solve this problem, such as change the texture import settings?** 

Thanks for your 素晴らしい work!! 

PS: the model I tested is below.
[mark_free_zh.zip](https://github.com/user-attachments/files/16975882/mark_free_zh.zip)

**Comment by MizunagiKB** [comment]
@Jueast 
Thank you for your feedback.

I must admit that I do not have a thorough understanding of shaders.
I ported the shaders by referring to the _GLSL_ and code provided in the **Live2D** sample code.

The issue of becoming black when semi-transparent has been a problem since the initial release, and it has been reported in Issues as well.
I had given up, thinking that the shaders I ported were insufficient.

I am very pleased that your proposed fix seems to resolve the issue!

Although I can write the code myself, since you discovered the bug fix, would you kindly submit a pull request?

If you are willing to submit a pull request, please do so to the active development branch at https://github.com/MizunagiKB/gd_cubism/tree/0.7.

**Comment by Jueast** [comment]
@MizunagiKB 
Thanks for your comment.
I have submitted my pull request#114 and try to explain the origin of the problem there, please check it. :)
I do have met similiar problem you mentioned about animation change, and I found it was also ok after my commit for the opacity. 
I am very glad to help you perfect your work! 
Have a nice day.
