### ISSUE TITLE
I opened the demo in Godot 4.3 but it's now working?

### ISSUE THREAD

**Issue by madcoffee** [MizunagiKB/gd_cubism#118]
I'm sorry, but I am not a programmer and I did follow the [Build instructions](https://mizunagikb.github.io/gd_cubism/gd_cubism/0.6/en/build.html) and opened the demo. Did I do something wrong?

![image](https://github.com/user-attachments/assets/f97d6509-acf7-4a4e-94bb-c173021e0622)

**Comment by MizunagiKB** [comment]
Thank you for reporting this issue.

Upon reviewing the screenshot you provided, it appears that the **libgd_cubism.windows.x86_64.dll** file is missing from your environment.

Due to licensing restrictions, **GDCubism** cannot provide pre-built binaries.
Therefore, you will need to build **GDCubism** yourself or seek assistance from someone knowledgeable to create the necessary binaries.

The following page contains instructions on how to build GDCubism:

> [Build Instructions](https://mizunagikb.github.io/gd_cubism/gd_cubism/0.6/en/build.html)

If you do not have anyone to assist you, you will need to perform the build process yourself.
First, ensure you have all the necessary tools and dependencies.

**Comment by madcoffee** [comment]
Ah thanks, I finally understood. I didn't compile it right
