### ISSUE TITLE
Error - file not found

### ISSUE THREAD

**Issue by m00nk** [MizunagiKB/gd_cubism#14]
I have tried to compile the last version of the extension and I have got the error 
```
src/gd_cubism_motion_entry.hpp:8:10: fatal error: Motion/CubismExpressionMotionManager.hpp: No such file or directory
    8 | #include <Motion/CubismExpressionMotionManager.hpp>
```

I'm using **Cubism SDK For Native v.4 r7** and it has no file `Framework/src/Motion/CubismExpressionMotionManager.hpp`.

**Comment by MizunagiKB** [comment]
I checked the contents of Cubism 4 SDK for Native R7.
As you pointed out, the file Framework/src/Motion/CubismExpressionMotionManager.hpp does not exist.

It is possible that you selected the Cubism 4 SDK for Native R7 due to the Cubism 5 SDK being in beta.
However, GDCubism is designed to operate with the Cubism 5 SDK for Native R1 beta1.

Therefore, I would suggest attempting to rebuild using the Cubism 5 SDK for Native R1 beta1.

> Although it is still only available on GitHub, the new Framework will also be able to receive motion playback signals.

**Comment by m00nk** [comment]
Thank you for explanation.
